### ISSUE TITLE
SeeEnteredRooms thread.sleep?

### ISSUE THREAD

**Issue by AllBill127** [AllBill127/Skestam_Kartu#53]
SeeEnteredRooms line 45 has a questionable while with threadSleep. Could this be redone in some other way that wouldnt sleep the thread?

**Comment by Eitsop** [comment]
This might be help: https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.join?view=net-6.0
Basically you could do:

            tReadRooms.Join();
            tReadUsers.Join();

The .Join() will block until the thread has completed.
